### PR TITLE
Update project to .NET Core

### PR DESCRIPTION
**Pull request by qubitz**
Hi, really love how simple and beautiful this program is. However, I'm struggling to implement it into my CI on linux without manually downloading the binaries from the nuget website beforehand since I have no existing project on which to add this package.

This project should be updated to .NET Core so that it can be used as a [.NET Core tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) like so:
```cmd
> dotnet tool install -g extent
(...installs 'extent' to path...)
> extent -i <test-results>.xml -o <test-report>.html
```
This has two benefits:
1. Doesn't need a project to install from commandline
  `dotnet add package extent` command can only add to existing projects
2. Cross-platform executable automatically gets set in path with `dotnet tool install -g extent`
3. Can still be used as a regular nuget package

### CODE REVIEW

**Comment by gep13** [comment]
@anshooarora @dsparkplug I was curious about whether it was planned to bring in this change, and to publish as a .Net Global Tool.  I have a project where I am looking to bring in the extent cli, and having it as a Global Tool would make things a little easier.

**Comment by gep13** [comment]
@qubitz do you think it would make sense to make the .Net Global Tool package called extent.Tool?  This seems to be a convention I have seen for a few projects where they have both a .Net Framework version, and a .net Global Tool version.

**Comment by brandonmcclure** [comment]
Running this in core would help my desire to run this in a linux container, and might help with issue #30 and make it more portable in general. I made a fork of @qubitz's fork to create a Docker image running on a linux .net core image, which is working for me to display the results of pester tests.  I had to bump the ExtentReports dependency to 4.1 and then add a reference to `System.Configuration.ConfigurationManager`, but other than that this branch seems to work well for me. 

I cannot speak to the use as a .net global tool, but imo this is a useful PR.

https://github.com/brandonmcclure/extentreports-dotnet-cli

**Comment by brandonmcclure** [comment]
@anshooarora @dsparkplug Is there anything I can do to help complete this PR? This tool is really handy for replicating my CI pipeline locally and getting a nice report/feedback. I have been using qubitz fork/branch on and off since 12/2020 and I really enjoy the cross platform capabilities of .net core and would love to see this change merged in so that more people can use this software.

**Comment by sebastienpa** [comment]
+1 Guys please merge this and release so we can use it for cross-platform development 🙏 

 I have looked around for alternatives and it seems there are none

**Comment by anshooarora** [comment]
I haven't been able to test it yet, will try to do it soon and publish to nuget.

**Comment by keys1234249** [comment]
Thank you!

**Pull request merged**
